config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  validates :message, presence: true
  after_create :send_comment_email

  RATINGS = {
    '5 stars': 5.0,
    '4 stars': 4.0,
    '3 stars': 3.0,
    '2 stars': 2.0,
    '1 star': 1.0,
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
      NotificationMailer.comment_added(self).deliver_now
  end


end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :place
  mount_uploader :picture, PictureUploader
  validates :picture, presence: true
  
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :photos, dependent: :destroy
  geocoded_by :address
  after_validation :geocode
  validates :name, presence: true, length: { minimum: 3 }
  validates :address, presence: true
  validates :description, presence: true

  def average2
    @comments = self.comments
    @comments.sum/@comments.length
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @pagy, @places = pagy(Place.all, items: 5)
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end


  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @place.update_attributes(place_params)
    redirect_to root_path
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end


  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end

  def average_rating
    @place.comments.sum/@place.comments.length
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster DC - Best Happy Hours in DC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>

<nav class="navbar navbar">
  <%= link_to 'Nomster', root_path, class: 'navbar-brand col-3' %>
      
      
      <div class="justify-content-end">
  <!--      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button> -->

      
     
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to new_place_path, class: 'nav-link ' do %>
              <i class="fa fa-plus-circle"></i>
              New Place
            <% end %>
          </li>
          <!---- <div class="collapse navbar-collapse">  -->
       <% if user_signed_in? %>
         <li class="nav-item"> 
          <span class="nav-link"><%= link_to 'My Profile', user_path(current_user) %></span>
        </li><br/><br/>
          <li class="nav-item">
          <span class="nav-link"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></span>
          </li>
          

         <% else %>
          <li class="nav-item">
              <span class="nav-link"><%= link_to "Sign In", new_user_session_path %></span>
            </li> <br/><br/>
          <li class="nav-item">
              <span class="nav-link"><%= link_to "Sign Up", new_user_registration_path %></span>
            </li>
          </ul>
        <% end %>
      </div>
   
</nav>       
    
   
    <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
 <h1>Edit - <%= @place.name %></h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="4"></li> 
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'nom-slide-image-1.jpg', class: 'img-fluid' %>
      <div class="carousel-caption">
      <h3>Find Your Next Happy Hour Spot</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'nom-slide-image-2.jpg', class: 'img-fluid' %>
    </div>
<div class="carousel-item">
      <%= image_tag 'nom-slide-image-3.jpg', class: 'img-fluid' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'nom-slide-image-4.jpg', class: 'img-fluid' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'nom-slide-image-5.jpg', class: 'img-fluid' %>
    </div> 
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<% @places.each do |place| %>
  <div class="booyah-box col-10 offset-1">
      <h1><%= link_to place.name, place_path(place) %></h1>
      <i><%= place.address %></i><br /><br />
      <p><%= place.description %></p><br />

      <% if place.user.present? %>
        <small><%=place.user.email %></small>
      <% end %>

<!-- Comment Section place-->  
      <% if place.comments.present? %>
        <div class="col-12">
          <blockquote>
            <% if place.comments.last.humanized_rating.present? %>
              <b><%= place.comments.last.humanized_rating %></b> -
            <% end %>
            <%= place.comments.last.message %>
            <small><%= place.comments.last.user.email %></small>
          </blockquote>
        </div>
      <% end %>

<!------ Photo of place ----->      

      <div class="row justify-content-center">
        <% if place.photos.present? %>
          <%= image_tag place.photos.last.picture.url.to_s, class: "img-fluid mx-auto d-block", alt: "Responsive image"%>
        </div>
      <div class="row justify-content-center">
        <%= place.photos.last.caption %>
      </div>
      <div class="row justify-content-center">
          <small><%= place.photos.last.user.email %></small>
        <% end %>
      </div> 
  </div>
<% end %>

<!-- Pagination -->

<div class="pagy-style col-4 offset-4">
  <%== pagy_bootstrap_nav(@pagy) %>
  <%== pagy_bootstrap_nav_js(@pagy) %>
</div>

<br/>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
 <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name, placeholder: "DC Bar Name Here" %>
    <%= f.input :address, placeholder: "123 DC St, Washington DC 20001" %>
    <%= f.input :description, placeholder: "Ex: This place is a hole in the wall, but in the best way! or Their happy hour is extended until 8pm from Tuesday to Thursday!" %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br/><br/>
  <p><%= @place.description %></p>


<!-- Edit/Remove -->
      <div class="text-right">  
        <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#photoModal">Add a Photo</button>
        <% if current_user && current_user == @place.user %>
        <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
        <%= link_to 'Remove Location', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this location'}, class: 'btn btn-danger' %>
      <% end %>
    </div>
<br />


<!-- Photo Section-->

 <!-- Picture Modal -->
  <div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">Add a Photo</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          
        </div>
        
        <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
          <div class="modal-body">
              <%= f.input :picture %>
              <%= f.input :caption, placeholder: "Look at their outdoor patio! -or- They have the best nachos, just look at them!" %>
              </div>
              
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Add a Photo", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<!-- Title and Button for photo modal -->
<h1 class="float-left">Pictures</h1>
      <div class="clear"></div>
 

<!-- list of photos and captins-->
<br/>

    <div class="row">
        <% @place.photos.each do |photo| %>
          <div class="col-12 col-sm-4 justify-content-center">
              <%= image_tag photo.picture.url.to_s, class: "img-fluid mx-auto d-block", alt: "Responsive image" %><br/>
          <p class="text-center"><%= photo.caption %></p><br/>
          <p class="text-center"><small><%= photo.user.email %></small></p>
          
          </div>
        <% end %>
    </div>
  

<br/>

<!-- Comment Section -->
<!-- Model section - how to add comment -->
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
          <div class="modal-body">
              <%= f.input :message, placeholder: "Ex: This place is known for their cocktails, try their special martini!" %>
              <%= f.input :rating, label: "Rating - Be honest, tell us what you think.", as: :select, collection: Comment::RATINGS %>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Title and button for comment -->
<h1 class="float-left">Comments</h1>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary btn-md float-right" data-toggle="modal" data-target="#commentModal">
    Add a comment
</button>

<div class="clear"></div>

  
    <div class="row  justify-content-center">
      <div class="col-5 offset-1">
        <% @place.comments.each do |comment| %>
        
          <blockquote>
            <% if comment.humanized_rating.present? %>
              <b><%= comment.humanized_rating %></b> -
            <% end %>
              <%= comment.message %>
              <small><%= comment.user.email %></small>
          </blockquote>
        <% end %>
      </div>


    <!-------------- This is where the rating card lives  ---->
      <div class="col-6">  
          <br/>
          <div class="card-group col-10 offset-md-1">    
            <div class="card text-center">
              <div class="card-body ">

                <br/>
             
                <h2 class="card-title"><%= @place.comments.average(:rating).round(2) %></h2>
                      
                      <% if @place.comments.present? && @place.comments.average(:rating) >= 4.5 %>
                        <h3><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></h3>
                      <% elsif @place.comments.present? && @place.comments.average(:rating) >= 3.8 %> 
                        <h3><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i></h3>
                      <% elsif @place.comments.present? && @place.comments.average(:rating) >= 2.8 %> 
                        <h3><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i></h3>
                      <% elsif @place.comments.present? && @place.comments.average(:rating) >= 1.8 %> 
                        <h3><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i></h3>
                      <% elsif @place.comments.present? && @place.comments.average(:rating) >= 0.8 %> 
                        <h3><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i></h3>
                      <% else %>   
                        <h3><i class="fa fa-star-0" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i></h3>
                      <% end %>
                  <p class="card-text">
                    <i class="fa fa-user" aria-hidden="true"></i> <%= @place.comments.count %> of reviews
                  </p>
                    <br/>
         <!----- progress part part of the card ---->
                
                <div class="progress">
                  <div class="progress-bar-rating" role="progressbar" style="width: 10%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><i class="fa fa-star" aria-hidden="true"></i> 5</div>
                  <div class="progress-bar" role="progressbar" style="width: <%= @place.comments.where(rating: 5.0).count*100/@place.comments.count if @place.comments.present? %>%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>

                <div class="progress">
                  <div class="progress-bar-rating" role="progressbar" style="width: 10%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><i class="fa fa-star" aria-hidden="true"></i> 4</div>
                  <div class="progress-bar" role="progressbar" style="width: <%= @place.comments.where(rating: 4.0).count*100/@place.comments.count if @place.comments.present? %>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar-rating" role="progressbar" style="width: 10%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><i class="fa fa-star" aria-hidden="true"></i> 3</div>
                  <div class="progress-bar" role="progressbar" style="width:<%= @place.comments.where(rating: 3.0).count*100/@place.comments.count if @place.comments.present? %>%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar-rating" role="progressbar" style="width: 10%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><i class="fa fa-star" aria-hidden="true"></i> 2</div>
                  <div class="progress-bar" role="progressbar" style="width: <%= @place.comments.where(rating: 2.0).count*100/@place.comments.count if @place.comments.present? %>%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <div class="progress">
                  <div class="progress-bar-rating" role="progressbar" style="width: 11%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><i class="fa fa-star" aria-hidden="true"></i> 1</div>
                   <div class="progress-bar" role="progressbar" style="width: <%= @place.comments.where(rating: 1.0).count*100/@place.comments.count if @place.comments.present? %>%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                
              </div>
            </div>
          </div>
        
     
    </div>
  </div>

  <br/>

<!-- Map Function -->
  <% if @place.latitude.present? && @place.longitude.present? %>
    <script>

      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 14,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyABtClcCssJptUprlpkaG44X-BwENKR_a0&callback=initMap">
    </script>

     <div id="map"></div>
<% end %>




</div>





<br/><br/>

app/views/users/show.html.erb
<div class="booyah-box">
  <div class="row">
      <div class="col-4">
          <%= image_tag 'user-icon.png' %>
      </div>

      <div class="col-8">
        <h1><%= @user.email %></h1>
        <h3>Member Since: <%= @user.created_at.strftime("%B, %Y") %></h3>
        <h4><%= @user.comments.count %> total comments </h4>
        <h4><%= @user.comments.where(rating: 5).count %> total of 5 star reviews </h4>
      </div>
    </div>
    <div class="clear"></div>
</div>

<!-- Comment Section -->
<br /><br />
<div class="booyah-box col-10 offset-1">
<h1 class="text-center">My Comments</h1>
<br /><br />
<div class="row">

  <% @user.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
      <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>

</div>

<!-- Places Section -->

<div class="clear"></div>
<br /><br />
<h1 class="text-center">My Places</h1>
<br /><br />
  <!-- Place section-->
  <% @user.places.each do |place| %>
   <div class="booyah-box col-10 offset-1">
      <h1><%= link_to place.name, place_path(place) %></h1>
      <i><%= place.address %></i><br /><br />
      <p><%= place.description %></p><br />

      <% if place.user.present? %>
        <small><%=place.user.email %></small>
      <% end %>

      <!-- Comment Section-->
      <% if place.comments.present? %>
        <div class="col-12">
          <blockquote>
            <% if place.comments.last.humanized_rating.present? %>
              <b><%= place.comments.last.humanized_rating %></b> -
            <% end %>
            <%= place.comments.last.message %>
            <small><%= place.comments.last.user.email %></small>
            </blockquote>
          </div>
      <% end %>
    </div>
  <% end %>
</div>